# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HopeSow' do
  pod 'Facebook-iOS-SDK'
  pod 'Parse'
  pod 'ParseFacebookUtils'
end

target 'HopeSowTests' do

end

